// lib/dummyServices.ts
import type { Service } from './types';

export const services: Service[] = [
  {
    id: 's1',
    title: 'Ganesh Puja (Home)',
    description: 'Simple Ganesh puja for auspicious beginnings - 30 minutes.',
    durationMinutes: 30,
    priceINR: 501,
    image: '/images/ganesh.jpg',
  },
  {
    id: 's2',
    title: 'Satyanarayan Puja',
    description: 'Family ritual for prosperity and blessings - 60 minutes.',
    durationMinutes: 60,
    priceINR: 1501,
    image: '/images/satyanarayan.jpg',
  },
  {
    id: 's3',
    title: 'Havan / Yajna',
    description: 'Special havan for health and peace - 90 minutes.',
    durationMinutes: 90,
    priceINR: 3501,
    image: '/images/havan.jpg',
  },
  {
    id: 's4',
    title: 'Lakshmi Puja',
    description: 'Worship of Goddess Lakshmi for wealth and prosperity - 45 minutes.',
    durationMinutes: 45,
    priceINR: 751,
    image: '/images/lakshmi.jpg',
  },
  {
    id: 's5',
    title: 'Navratri Puja',
    description: 'Special puja during Navratri festival for divine blessings - 60 minutes.',
    durationMinutes: 60,
    priceINR: 1201,
    image: '/images/navratri.jpg',
  },
  {
    id: 's6',
    title: 'Griha Pravesh Puja',
    description: 'House warming ceremony for new home - 75 minutes.',
    durationMinutes: 75,
    priceINR: 2501,
    image: '/images/griha-pravesh.jpg',
  },
  {
    id: 's7',
    title: 'Vastu Shanti Puja',
    description: 'Vastu dosh rectification ceremony - 90 minutes.',
    durationMinutes: 90,
    priceINR: 3501,
    image: '/images/vastu.jpg',
  },
  {
    id: 's8',
    title: 'Wedding Ceremony',
    description: 'Complete wedding rituals and ceremonies - 180 minutes.',
    durationMinutes: 180,
    priceINR: 7501,
    image: '/images/wedding.jpg',
  },
  {
    id: 's9',
    title: 'Rudrabhishek Puja',
    description: 'Special puja dedicated to Lord Shiva - 60 minutes.',
    durationMinutes: 60,
    priceINR: 1501,
    image: '/images/rudrabhishek.jpg',
  },
  {
    id: 's10',
    title: 'Birthday Puja',
    description: 'Special puja for birthday celebrations and longevity - 45 minutes.',
    durationMinutes: 45,
    priceINR: 751,
    image: '/images/birthday.jpg',
  },
  {
    id: 's11',
    title: 'Mundan Sanskar',
    description: 'First haircut ceremony for infants - 60 minutes.',
    durationMinutes: 60,
    priceINR: 1501,
    image: '/images/mundan.jpg',
  },
  {
    id: 's12',
    title: 'Anniversary Puja',
    description: 'Special puja for wedding anniversaries - 45 minutes.',
    durationMinutes: 45,
    priceINR: 1001,
    image: '/images/anniversary.jpg',
  }
];
